### ISSUE TITLE
All non student roles display Instructor view

### ISSUE THREAD

**Issue by kenaragon** [sakaicontrib/attendance#32]
The Instructor view is given to all roles not listed as 'Student'.  If you have a custom role, guest role, ect, they will be presented with the Instructor view.  This should be changed to use a permission to check for instructor level permissions like 'site.upd' or have a set of permissions that can be checked or unchecked from the realms tool

`if(this.role != null && this.role.equals("Student")){`

**Comment by davidpbauer** [comment]
Thanks for creating this issue. We will be working on a refactor of Attendance, aimed at Sakai 13.x, which changes the tool to be permission-based instead of role-based as well as other needed upgrades. If you have any other specific permissions that you would like to be configurable (create attendance item, take attendance, grade, view grades, etc.) please let me know and I'll add it to my notes.

**Comment by adrianfish** [comment]
@davidpbauer Have you made a start on the refactor, yet? Longsight are likely going to be working on making attendance permissions based, at least one of our clients wants that to happen. We don't want to duplicate efforts.

**Comment by davidpbauer** [comment]
Hi @adrianfish. We haven't started this work yet, but we're meeting March 14 to prioritize our development projects between now and August 2019. The attendance refactor and improvements are on our list, so whether it's this or another issue/improvement we will be working on the tool this Spring/Summer.

I definitely agree that we don't want to duplicate efforts, so perhaps we should continue to discuss as Longsight determines what they need to support this tool.

**Comment by adrianfish** [comment]
@davidpbauer How did the meeting go? We've a client who wants us to work on the permissions side of things, so we'll probably get on with that unless you've got that work scheduled over the new month or so. Need to get that work signed off, but that's the timescale.

**Comment by davidpbauer** [comment]
Hi @adrianfish. Our meeting went well. By the end of May, we plan to finish our upgrade to 12.6 and all of the attendance work. Since you are on such a tight timeline, it may be best if you start on the permissions work because we are tackling our upgrade to 12.6 first. Our other Attendance goals include improving performance (especially in large sites with lots of items), a feature for students to check in themselves, and some general styling and code cleanup.

I'd be happy to collaborate on the permissions work if you want to lead that effort but need an extra hand.
